### ISSUE TITLE
Impossible d'obtenir le contenu du Qr-Code

### ISSUE THREAD

**Issue by Azzedine33** [Egsagon/turboself-api#1]
Impossible d'obtenir le contenu du Qr-Code. En effet, cette fonction est... vide ?
Quelqu'un pour patch ça ? Peut-être que le code a été effacé par erreur. Si besoin, je peux prêter un compte Turboself

**Comment by Egsagon** [comment]
Salut,

De ce que je me rappelle (et ça à peut-être changé), le QR code est généré par la frontend de TurboSelf, et certaines parties du script sont obfusquées (je sais pas pourquoi et je veut pas savoir).

Il faudrait tout décrypter et traduire en python, mais comme je n'utilise plus TS, j'abandonne le projet.

Si tu veut juste un moyen simple de récupérer un QR, essaye de prendre un screenshot avec un navigateur automatisé (selenium, plw, etc.

**Comment by Azzedine33** [comment]
Salut,
Merci pour ta réponse ! Pas grave, je ferais autrement. J’aimerais créer pour mon lycée une page pour télécharger sa carte Turboself dans l’app Wallet sur iOS et Android. Ton script est tellement top que pense pouvoir m’en servir pour authentifier les élèves (on m’a refusé l’accès OAuth à l’ENT 😭), et si c’est assez rapide mettre à jour le solde restant sur la carte.
En tous cas merci pour ton travail c’est génial

**Comment by Egsagon** [comment]
Je vois pas trop le besoin, perso j'utilisai jamais la carte, juste l'appli myturboself mais bon bonne chance quand meme :D

**Comment by Azzedine33** [comment]
Oui enfin l’app ou la carte, ca marchera avec les deux. L’avantage est plus présent sur iOS, car on a une notif sur l’écran verrouillé au lycée, et ceux qui ont une montre connectée peuvent avoir le qr code dessus.
Bref projet amusant 😅 je te dirais si je suis allé jusqu’au bout. D’ailleurs pour les crédits je dois te mentionner comment ?

**Comment by Egsagon** [comment]
> D’ailleurs pour les crédits je dois te mentionner comment ?

Fait ce que tu veux avec le repo, je peut meme te le donner de toute façon ca me sert plus. Mon projet c'était un bot discord qui te rapelle quand t'as oublié de réserver mais plus besoin maintenant
